import { describe, expect, it } from 'vitest';
import { demoCategories, demoProjectFixtures, generateRequirements, initialProjects } from '@/demo/demoData';
import { lifecycleActions } from '@/features/requirements/requirementActions';
import { clampSplitter, initialWorkspaceState, workspaceReducer } from '@/state/workspaceReducer';
import { loadWorkspaceState, WORKSPACE_STATE_KEY } from '@/state/sessionPersistence';

describe('demo data',()=>{it('creates eight projects with counts from requirements',()=>{const reqs=generateRequirements(); expect(demoProjectFixtures).toHaveLength(8); expect(initialProjects().map(p=>p.requirementCount)).toEqual(demoProjectFixtures.map(p=>reqs.filter(r=>r.projectId===p.id).length));}); it('keeps category type and visible key consistent',()=>{const cats=new Map(demoCategories.map(c=>[c.key,c])); const keys=new Set<string>(); for(const r of generateRequirements()){expect(r.type).toBe(cats.get(r.categoryKey)?.type); expect(r.visibleKey.startsWith(r.type)).toBe(true); expect(keys.has(r.visibleKey)).toBe(false); keys.add(r.visibleKey);}}); it('project fixtures have no icon property',()=>{expect(demoProjectFixtures.some(p=>'icon' in p)).toBe(false);});});
describe('workspace reducer',()=>{it('prevents duplicate tabs',()=>{let s=workspaceReducer(initialWorkspaceState,{type:'openRequirementTab',requirementId:'r1',visibleKey:'FR-AUTH-0001'}); s=workspaceReducer(s,{type:'openRequirementTab',requirementId:'r1',visibleKey:'FR-AUTH-0001'}); expect(s.openRequirementTabs).toHaveLength(1);}); it('closes active tab back to workspace',()=>{let s=workspaceReducer(initialWorkspaceState,{type:'openRequirementTab',requirementId:'r1',visibleKey:'FR-AUTH-0001'}); s=workspaceReducer(s,{type:'closeTab',tabId:'req-tab-r1'}); expect(s.activeAppTabId).toBe('workspace');}); it('clamps splitter',()=>{expect(clampSplitter(0)).toBe(.25); expect(clampSplitter(1)).toBe(.8);});});
describe('actions and persistence',()=>{it('maps lifecycle actions',()=>{expect(lifecycleActions('draft')).toEqual(['Edit','Approve','Reject']); expect(lifecycleActions('implemented')).toEqual([]); expect(lifecycleActions('obsolete')).toEqual([]);}); it('recovers corrupt session state',()=>{sessionStorage.setItem(WORKSPACE_STATE_KEY,'bad'); expect(loadWorkspaceState()).toEqual(initialWorkspaceState);});});
