// Generated from: test/e2e/features/requirements.feature
import { test } from "playwright-bdd";

test.describe('Project requirements', () => {

  test('User opens project requirements', async ({ Given, When, Then, page }) => { 
    await Given('the backend contains a requirement test project named "Requirement BDD Project" with requirements', {"dataTable":{"rows":[{"cells":[{"value":"categoryKey"},{"value":"categoryType"},{"value":"categoryName"},{"value":"description"},{"value":"priority"},{"value":"owner"},{"value":"source"}]},{"cells":[{"value":"AUTH"},{"value":"FR"},{"value":"Authentication"},{"value":"Users can sign in."},{"value":"p1"},{"value":"Alice"},{"value":"Security policy"}]},{"cells":[{"value":"PERF"},{"value":"NFR"},{"value":"Performance"},{"value":"The dashboard opens within one second."},{"value":"p2"},{"value":"Bob"},{"value":"SLA"}]}]}}); 
    await When('I open the requirements list for the requirement test project', null, { page }); 
    await Then('the requirements table should show the requirements', {"dataTable":{"rows":[{"cells":[{"value":"key"},{"value":"status"},{"value":"description"},{"value":"priority"},{"value":"owner"}]},{"cells":[{"value":"FR-AUTH-0001"},{"value":"Draft"},{"value":"Users can sign in."},{"value":"p1"},{"value":"Alice"}]},{"cells":[{"value":"NFR-PERF-0001"},{"value":"Draft"},{"value":"The dashboard opens within one second."},{"value":"p2"},{"value":"Bob"}]}]}}, { page }); 
  });

  test('User sees the sidebar requirements counter', async ({ Given, When, Then, page }) => { 
    await Given('the backend contains a requirement test project named "Requirement BDD Project" with requirements', {"dataTable":{"rows":[{"cells":[{"value":"categoryKey"},{"value":"categoryType"},{"value":"categoryName"},{"value":"description"},{"value":"priority"},{"value":"owner"}]},{"cells":[{"value":"AUTH"},{"value":"FR"},{"value":"Authentication"},{"value":"Users can sign in."},{"value":"p1"},{"value":"Alice"}]},{"cells":[{"value":"PERF"},{"value":"NFR"},{"value":"Performance"},{"value":"The dashboard opens within one second."},{"value":"p2"},{"value":"Bob"}]}]}}); 
    await When('I open the application', null, { page }); 
    await Then('the sidebar should show requirement count 2 for project "Requirement BDD Project"', null, { page }); 
  });

  test('User opens project details with statistics', async ({ Given, When, Then, And, page }) => { 
    await Given('the backend contains a requirement test project named "Requirement BDD Project" with requirements', {"dataTable":{"rows":[{"cells":[{"value":"categoryKey"},{"value":"categoryType"},{"value":"categoryName"},{"value":"description"},{"value":"priority"},{"value":"owner"}]},{"cells":[{"value":"AUTH"},{"value":"FR"},{"value":"Authentication"},{"value":"Users can sign in."},{"value":"p1"},{"value":"Alice"}]},{"cells":[{"value":"PERF"},{"value":"NFR"},{"value":"Performance"},{"value":"The dashboard opens within one second."},{"value":"p2"},{"value":"Bob"}]}]}}); 
    await When('I open the application', null, { page }); 
    await And('I open project "Requirement BDD Project" from the sidebar', null, { page }); 
    await Then('the requirement test project details should show statistics', {"dataTable":{"rows":[{"cells":[{"value":"categories"},{"value":"requirements"},{"value":"draft"},{"value":"approved"},{"value":"implemented"},{"value":"obsolete"},{"value":"rejected"}]},{"cells":[{"value":"2"},{"value":"2"},{"value":"2"},{"value":"0"},{"value":"0"},{"value":"0"},{"value":"0"}]}]}}, { page }); 
  });

  test('User selects a requirement', async ({ Given, When, Then, And, page }) => { 
    await Given('the backend contains a requirement test project named "Requirement BDD Project" with requirements', {"dataTable":{"rows":[{"cells":[{"value":"categoryKey"},{"value":"categoryType"},{"value":"categoryName"},{"value":"description"},{"value":"priority"},{"value":"owner"},{"value":"source"}]},{"cells":[{"value":"AUTH"},{"value":"FR"},{"value":"Authentication"},{"value":"Users can sign in."},{"value":"p1"},{"value":"Alice"},{"value":"Security policy"}]}]}}); 
    await When('I open the requirements list for the requirement test project', null, { page }); 
    await And('I select requirement "FR-AUTH-0001"', null, { page }); 
    await Then('the requirement details panel should show requirement "FR-AUTH-0001"', null, { page }); 
  });

  test('User sees the start review action for a selected draft requirement', async ({ Given, When, Then, And, page }) => { 
    await Given('the backend contains a requirement test project named "Requirement BDD Project" with requirements', {"dataTable":{"rows":[{"cells":[{"value":"categoryKey"},{"value":"categoryType"},{"value":"categoryName"},{"value":"description"},{"value":"priority"},{"value":"owner"},{"value":"source"}]},{"cells":[{"value":"AUTH"},{"value":"FR"},{"value":"Authentication"},{"value":"Users can sign in."},{"value":"p1"},{"value":"Alice"},{"value":"Security policy"}]}]}}); 
    await When('I open the requirements list for the requirement test project', null, { page }); 
    await And('I select requirement "FR-AUTH-0001"', null, { page }); 
    await Then('the Start review action should be visible', null, { page }); 
  });

  test('User copies a requirement key from the table', async ({ Given, When, Then, And, page }) => { 
    await Given('the backend contains a requirement test project named "Requirement BDD Project" with requirements', {"dataTable":{"rows":[{"cells":[{"value":"categoryKey"},{"value":"categoryType"},{"value":"categoryName"},{"value":"description"},{"value":"priority"},{"value":"owner"}]},{"cells":[{"value":"AUTH"},{"value":"FR"},{"value":"Authentication"},{"value":"Users can sign in."},{"value":"p1"},{"value":"Alice"}]}]}}); 
    await When('I open the requirements list for the requirement test project', null, { page }); 
    await And('I copy requirement key "FR-AUTH-0001"', null, { page }); 
    await Then('the requirement key copied toast should be visible for requirement "FR-AUTH-0001"', null, { page }); 
  });

  test('User opens a requirement details tab', async ({ Given, When, Then, And, page }) => { 
    await Given('the backend contains a requirement test project named "Requirement BDD Project" with requirements', {"dataTable":{"rows":[{"cells":[{"value":"categoryKey"},{"value":"categoryType"},{"value":"categoryName"},{"value":"description"},{"value":"priority"},{"value":"owner"}]},{"cells":[{"value":"AUTH"},{"value":"FR"},{"value":"Authentication"},{"value":"Users can sign in."},{"value":"p1"},{"value":"Alice"}]}]}}); 
    await When('I open the requirements list for the requirement test project', null, { page }); 
    await And('I double-click requirement "FR-AUTH-0001"', null, { page }); 
    await Then('the URL should point to the details route for requirement "FR-AUTH-0001"', null, { page }); 
    await And('the tab bar should contain "FR-AUTH-0001"', null, { page }); 
    await And('the full requirement details page should show requirement "FR-AUTH-0001"', null, { page }); 
  });

  test('User closes a requirement details tab', async ({ Given, When, Then, And, page }) => { 
    await Given('the backend contains a requirement test project named "Requirement BDD Project" with requirements', {"dataTable":{"rows":[{"cells":[{"value":"categoryKey"},{"value":"categoryType"},{"value":"categoryName"},{"value":"description"},{"value":"priority"},{"value":"owner"}]},{"cells":[{"value":"AUTH"},{"value":"FR"},{"value":"Authentication"},{"value":"Users can sign in."},{"value":"p1"},{"value":"Alice"}]}]}}); 
    await And('I opened the requirement details tab for requirement "FR-AUTH-0001"', null, { page }); 
    await When('I close the "FR-AUTH-0001" tab', null, { page }); 
    await Then('the URL should point to the requirements list route', null, { page }); 
    await And('the requirements table should be visible again', null, { page }); 
  });

  test('User opens a requirement details route directly', async ({ Given, When, Then, And, page }) => { 
    await Given('the backend contains a requirement test project named "Requirement BDD Project" with requirements', {"dataTable":{"rows":[{"cells":[{"value":"categoryKey"},{"value":"categoryType"},{"value":"categoryName"},{"value":"description"},{"value":"priority"},{"value":"owner"}]},{"cells":[{"value":"AUTH"},{"value":"FR"},{"value":"Authentication"},{"value":"Users can sign in."},{"value":"p1"},{"value":"Alice"}]}]}}); 
    await When('I open the requirement details URL directly for requirement "FR-AUTH-0001"', null, { page }); 
    await Then('the tab bar should contain "FR-AUTH-0001"', null, { page }); 
    await And('the full requirement details page should show requirement "FR-AUTH-0001"', null, { page }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('test/e2e/features/requirements.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":6,"pickleLine":3,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the backend contains a requirement test project named \"Requirement BDD Project\" with requirements","stepMatchArguments":[{"group":{"start":54,"value":"\"Requirement BDD Project\"","children":[{"start":55,"value":"Requirement BDD Project","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When I open the requirements list for the requirement test project","stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the requirements table should show the requirements","stepMatchArguments":[]}]},
  {"pwTestLine":12,"pickleLine":14,"tags":[],"steps":[{"pwStepLine":13,"gherkinStepLine":15,"keywordType":"Context","textWithKeyword":"Given the backend contains a requirement test project named \"Requirement BDD Project\" with requirements","stepMatchArguments":[{"group":{"start":54,"value":"\"Requirement BDD Project\"","children":[{"start":55,"value":"Requirement BDD Project","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":14,"gherkinStepLine":19,"keywordType":"Action","textWithKeyword":"When I open the application","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":20,"keywordType":"Outcome","textWithKeyword":"Then the sidebar should show requirement count 2 for project \"Requirement BDD Project\"","stepMatchArguments":[{"group":{"start":42,"value":"2"},"parameterTypeName":"int"},{"group":{"start":56,"value":"\"Requirement BDD Project\"","children":[{"start":57,"value":"Requirement BDD Project","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":18,"pickleLine":22,"tags":[],"steps":[{"pwStepLine":19,"gherkinStepLine":23,"keywordType":"Context","textWithKeyword":"Given the backend contains a requirement test project named \"Requirement BDD Project\" with requirements","stepMatchArguments":[{"group":{"start":54,"value":"\"Requirement BDD Project\"","children":[{"start":55,"value":"Requirement BDD Project","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":20,"gherkinStepLine":27,"keywordType":"Action","textWithKeyword":"When I open the application","stepMatchArguments":[]},{"pwStepLine":21,"gherkinStepLine":28,"keywordType":"Action","textWithKeyword":"And I open project \"Requirement BDD Project\" from the sidebar","stepMatchArguments":[{"group":{"start":15,"value":"\"Requirement BDD Project\"","children":[{"start":16,"value":"Requirement BDD Project","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then the requirement test project details should show statistics","stepMatchArguments":[]}]},
  {"pwTestLine":25,"pickleLine":33,"tags":[],"steps":[{"pwStepLine":26,"gherkinStepLine":34,"keywordType":"Context","textWithKeyword":"Given the backend contains a requirement test project named \"Requirement BDD Project\" with requirements","stepMatchArguments":[{"group":{"start":54,"value":"\"Requirement BDD Project\"","children":[{"start":55,"value":"Requirement BDD Project","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":27,"gherkinStepLine":37,"keywordType":"Action","textWithKeyword":"When I open the requirements list for the requirement test project","stepMatchArguments":[]},{"pwStepLine":28,"gherkinStepLine":38,"keywordType":"Action","textWithKeyword":"And I select requirement \"FR-AUTH-0001\"","stepMatchArguments":[{"group":{"start":21,"value":"\"FR-AUTH-0001\"","children":[{"start":22,"value":"FR-AUTH-0001","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":29,"gherkinStepLine":39,"keywordType":"Outcome","textWithKeyword":"Then the requirement details panel should show requirement \"FR-AUTH-0001\"","stepMatchArguments":[{"group":{"start":54,"value":"\"FR-AUTH-0001\"","children":[{"start":55,"value":"FR-AUTH-0001","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":32,"pickleLine":41,"tags":[],"steps":[{"pwStepLine":33,"gherkinStepLine":42,"keywordType":"Context","textWithKeyword":"Given the backend contains a requirement test project named \"Requirement BDD Project\" with requirements","stepMatchArguments":[{"group":{"start":54,"value":"\"Requirement BDD Project\"","children":[{"start":55,"value":"Requirement BDD Project","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":34,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When I open the requirements list for the requirement test project","stepMatchArguments":[]},{"pwStepLine":35,"gherkinStepLine":46,"keywordType":"Action","textWithKeyword":"And I select requirement \"FR-AUTH-0001\"","stepMatchArguments":[{"group":{"start":21,"value":"\"FR-AUTH-0001\"","children":[{"start":22,"value":"FR-AUTH-0001","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":36,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"Then the Start review action should be visible","stepMatchArguments":[]}]},
  {"pwTestLine":39,"pickleLine":49,"tags":[],"steps":[{"pwStepLine":40,"gherkinStepLine":50,"keywordType":"Context","textWithKeyword":"Given the backend contains a requirement test project named \"Requirement BDD Project\" with requirements","stepMatchArguments":[{"group":{"start":54,"value":"\"Requirement BDD Project\"","children":[{"start":55,"value":"Requirement BDD Project","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":41,"gherkinStepLine":53,"keywordType":"Action","textWithKeyword":"When I open the requirements list for the requirement test project","stepMatchArguments":[]},{"pwStepLine":42,"gherkinStepLine":54,"keywordType":"Action","textWithKeyword":"And I copy requirement key \"FR-AUTH-0001\"","stepMatchArguments":[{"group":{"start":23,"value":"\"FR-AUTH-0001\"","children":[{"start":24,"value":"FR-AUTH-0001","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":43,"gherkinStepLine":55,"keywordType":"Outcome","textWithKeyword":"Then the requirement key copied toast should be visible for requirement \"FR-AUTH-0001\"","stepMatchArguments":[{"group":{"start":67,"value":"\"FR-AUTH-0001\"","children":[{"start":68,"value":"FR-AUTH-0001","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":46,"pickleLine":57,"tags":[],"steps":[{"pwStepLine":47,"gherkinStepLine":58,"keywordType":"Context","textWithKeyword":"Given the backend contains a requirement test project named \"Requirement BDD Project\" with requirements","stepMatchArguments":[{"group":{"start":54,"value":"\"Requirement BDD Project\"","children":[{"start":55,"value":"Requirement BDD Project","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":48,"gherkinStepLine":61,"keywordType":"Action","textWithKeyword":"When I open the requirements list for the requirement test project","stepMatchArguments":[]},{"pwStepLine":49,"gherkinStepLine":62,"keywordType":"Action","textWithKeyword":"And I double-click requirement \"FR-AUTH-0001\"","stepMatchArguments":[{"group":{"start":27,"value":"\"FR-AUTH-0001\"","children":[{"start":28,"value":"FR-AUTH-0001","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":50,"gherkinStepLine":63,"keywordType":"Outcome","textWithKeyword":"Then the URL should point to the details route for requirement \"FR-AUTH-0001\"","stepMatchArguments":[{"group":{"start":58,"value":"\"FR-AUTH-0001\"","children":[{"start":59,"value":"FR-AUTH-0001","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":51,"gherkinStepLine":64,"keywordType":"Outcome","textWithKeyword":"And the tab bar should contain \"FR-AUTH-0001\"","stepMatchArguments":[{"group":{"start":27,"value":"\"FR-AUTH-0001\"","children":[{"start":28,"value":"FR-AUTH-0001","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":52,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"And the full requirement details page should show requirement \"FR-AUTH-0001\"","stepMatchArguments":[{"group":{"start":58,"value":"\"FR-AUTH-0001\"","children":[{"start":59,"value":"FR-AUTH-0001","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":55,"pickleLine":67,"tags":[],"steps":[{"pwStepLine":56,"gherkinStepLine":68,"keywordType":"Context","textWithKeyword":"Given the backend contains a requirement test project named \"Requirement BDD Project\" with requirements","stepMatchArguments":[{"group":{"start":54,"value":"\"Requirement BDD Project\"","children":[{"start":55,"value":"Requirement BDD Project","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":57,"gherkinStepLine":71,"keywordType":"Context","textWithKeyword":"And I opened the requirement details tab for requirement \"FR-AUTH-0001\"","stepMatchArguments":[{"group":{"start":53,"value":"\"FR-AUTH-0001\"","children":[{"start":54,"value":"FR-AUTH-0001","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":58,"gherkinStepLine":72,"keywordType":"Action","textWithKeyword":"When I close the \"FR-AUTH-0001\" tab","stepMatchArguments":[{"group":{"start":12,"value":"\"FR-AUTH-0001\"","children":[{"start":13,"value":"FR-AUTH-0001","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":59,"gherkinStepLine":73,"keywordType":"Outcome","textWithKeyword":"Then the URL should point to the requirements list route","stepMatchArguments":[]},{"pwStepLine":60,"gherkinStepLine":74,"keywordType":"Outcome","textWithKeyword":"And the requirements table should be visible again","stepMatchArguments":[]}]},
  {"pwTestLine":63,"pickleLine":76,"tags":[],"steps":[{"pwStepLine":64,"gherkinStepLine":77,"keywordType":"Context","textWithKeyword":"Given the backend contains a requirement test project named \"Requirement BDD Project\" with requirements","stepMatchArguments":[{"group":{"start":54,"value":"\"Requirement BDD Project\"","children":[{"start":55,"value":"Requirement BDD Project","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":65,"gherkinStepLine":80,"keywordType":"Action","textWithKeyword":"When I open the requirement details URL directly for requirement \"FR-AUTH-0001\"","stepMatchArguments":[{"group":{"start":60,"value":"\"FR-AUTH-0001\"","children":[{"start":61,"value":"FR-AUTH-0001","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":66,"gherkinStepLine":81,"keywordType":"Outcome","textWithKeyword":"Then the tab bar should contain \"FR-AUTH-0001\"","stepMatchArguments":[{"group":{"start":27,"value":"\"FR-AUTH-0001\"","children":[{"start":28,"value":"FR-AUTH-0001","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":82,"keywordType":"Outcome","textWithKeyword":"And the full requirement details page should show requirement \"FR-AUTH-0001\"","stepMatchArguments":[{"group":{"start":58,"value":"\"FR-AUTH-0001\"","children":[{"start":59,"value":"FR-AUTH-0001","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end